name: Test Routes using Postman and Newman

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.10.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          npm install 
          cd server
          npm install
      - name: Start Server and Run Tests
        run: |
          cd server
          npm start &
          sleep 5 &&
          cd .. &&
          npm run utests