name: CI - Integration Test 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
  - name: Check out code
  - uses: actions/checkout@master

  - name: Install dependencies
    run: npm install && cd server && npm install && npm start
  
  - name: Run tests 
    run: npm routes